prefix = 'user_app:'
# this for services
REDIS_LOCKING_ACCOUNT_PREFIX = f'{prefix}LOCKING_ACCOUNT'
REDIS_OTP_ATTEMPT_PREFIX = f'{prefix}OTP_ATTEMPT'
REDIS_OTP_CODE_PREFIX = f'{prefix}OTP_CODE'
REDIS_OTP_CODE_LOCK_PREFIX = f'{prefix}OTP_CODE_LOCK'

REDIS_TOTP_ATTEMPT_PREFIX = f'{prefix}TOTP_ATTEMPT'




REDIS_ACCOUNT_FORGOT_PASSWORD_PREFIX = f'{prefix}ACCOUNT_FORGOT_PASSWORD'
REDIS_ACCOUNT_FORGOT_PASSWORD_LOCK_PREFIX = f'{prefix}ACCOUNT_FORGOT_PASSWORD_LOCK'
REDIS_ACCOUNT_FORGOT_PASSWORD_ENCRYPT_KEY_PREFIX = f'{prefix}ACCOUNT_FORGOT_PASSWORD_ENCRYPT_KEY'

# this for views
