from .send_mail_login_failed_deactivate import send_mail_login_failed_deactivate
from .send_mail_otp_forgot_password import send_mail_otp_forgot_password
from .send_email_otp_login import send_email_otp_login