# Generated by Django 5.2.1 on 2025-05-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese')], default='vi', max_length=5),
        ),
    ]
