# Generated by Django 5.2.1 on 2025-05-24 18:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_profile_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twofactorauth',
            options={'verbose_name': 'Xác thực 2FA', 'verbose_name_plural': 'Xác thực 2FA'},
        ),
        migrations.CreateModel(
            name='Oauth2Token',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('expires_in', models.DateTimeField()),
                ('scope', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth2_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token OAuth2',
                'verbose_name_plural': 'Token OAuth2',
            },
        ),
    ]
