# Generated by Django 5.2.1 on 2025-05-24 19:45

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_twofactorauth_options_oauth2token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2token',
            name='access_token',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='refresh_token',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='twofactorauth',
            name='secret_key',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
