# Generated by Django 5.2.1 on 2025-05-25 19:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_profile_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'User Address', 'verbose_name_plural': 'User Address'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profile'},
        ),
        migrations.AlterModelOptions(
            name='twofactorauth',
            options={'verbose_name': '2FA Authentication', 'verbose_name_plural': '2FA Authentication'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
        migrations.CreateModel(
            name='UserTwoFactorAuthType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('totp', 'TOTP'), ('email', 'EMAIL')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth_type', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User 2FA type',
                'verbose_name_plural': 'User 2FA type',
            },
        ),
    ]
