# Generated by Django 5.2.1 on 2025-05-25 19:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_address_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeactivateReason',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('ban', 'Admin Ban'), ('spam', 'Spam Login'), ('other', 'Other')], max_length=50)),
                ('detail', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deactivate_reason', to=settings.AUTH_USER_MODEL)),
                ('user_deactivate', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_deactivate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Deactivate Reason',
                'verbose_name_plural': 'User Deactivate Reason',
            },
        ),
    ]
