# Generated by Django 5.2.1 on 2025-05-25 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_userdeactivatereason'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertwofactorauthtype',
            name='is_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usertwofactorauthtype',
            name='type',
            field=models.CharField(choices=[('totp', 'TOTP'), ('email', 'EMAIL')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usertwofactorauthtype',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth_type', to=settings.AUTH_USER_MODEL),
        ),
    ]
