# Generated by Django 5.2.1 on 2025-05-25 21:10

import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_usertwofactorauthtype_is_enable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='userdeactivatereason',
            name='user_deactivate',
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdeactivatereason',
            name='actor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_deactivate', to=settings.AUTH_USER_MODEL, verbose_name='Actor'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='address',
            name='geo_location',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Geo location'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Is default address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(max_length=50, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='address',
            name='ward',
            field=models.CharField(max_length=50, verbose_name='Ward'),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='access_token',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Access Token'),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='expires_in',
            field=models.DateTimeField(verbose_name='Expires in'),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='refresh_token',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Refresh Token'),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='scope',
            field=models.CharField(max_length=255, verbose_name='Scope'),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth2_token', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other'), (0, 'Not Say')], default=0, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese')], default='vi', max_length=5, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Is Staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Is Superuser'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verification',
            field=models.BooleanField(default=False, verbose_name='Verification status'),
        ),
        migrations.AlterField(
            model_name='userdeactivatereason',
            name='detail',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Detail'),
        ),
        migrations.AlterField(
            model_name='userdeactivatereason',
            name='reason',
            field=models.CharField(choices=[('ban', 'Admin Ban'), ('spam', 'Spam Login'), ('other', 'Other')], max_length=50, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='userdeactivatereason',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deactivate_reason', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='usertwofactorauthtype',
            name='is_enable',
            field=models.BooleanField(default=False, verbose_name='Enable 2FA'),
        ),
        migrations.AlterField(
            model_name='usertwofactorauthtype',
            name='type',
            field=models.CharField(choices=[('totp', 'TOTP'), ('email', 'EMAIL')], max_length=50, verbose_name='Type 2FA: TOTP or Email'),
        ),
        migrations.AlterField(
            model_name='usertwofactorauthtype',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth_type', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='usertwofactorauthtype',
            unique_together={('user', 'type')},
        ),
        migrations.CreateModel(
            name='TOTP',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_key', encrypted_model_fields.fields.EncryptedCharField(verbose_name='Secret Key')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': '2FA Authentication',
                'verbose_name_plural': '2FA Authentication',
            },
        ),
        migrations.DeleteModel(
            name='TwoFactorAuth',
        ),
    ]
