# Generated by Django 5.2.1 on 2025-05-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_remove_address_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertwofactorauthtype',
            name='is_priority',
            field=models.BooleanField(default=False, verbose_name='Priority 2FA'),
        ),
    ]
