# Generated by Django 5.2.1 on 2025-05-26 20:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_usertwofactorauthtype_is_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdeactivatereason',
            name='actor_detail',
            field=models.CharField(choices=[('system', 'System'), ('admin', 'Admin'), ('staff', 'Staff'), ('other', 'Other')], default=django.utils.timezone.now, max_length=50, verbose_name='Actor Detail'),
            preserve_default=False,
        ),
    ]
