# Generated by Django 5.2.1 on 2025-05-26 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_userdeactivatereason_actor_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdeactivatereason',
            old_name='actor_detail',
            new_name='reason_actor_detail',
        ),
        migrations.RenameField(
            model_name='userdeactivatereason',
            old_name='detail',
            new_name='reason_detail',
        ),
        migrations.RenameField(
            model_name='userdeactivatereason',
            old_name='reason',
            new_name='reason_type',
        ),
    ]
