# Generated by Django 5.2.1 on 2025-05-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_rename_actor_detail_userdeactivatereason_reason_actor_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdeactivatereason',
            name='email_send_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email send at'),
        ),
    ]
