# Generated by Django 5.2.1 on 2025-05-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_userdeactivatereason_email_send_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdeactivatereason',
            name='email_send_at',
        ),
    ]
