# Generated by Django 5.2.1 on 2025-05-27 15:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_remove_userdeactivatereason_email_send_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTwoFactorAuthSetting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('totp', 'TOTP'), ('email', 'EMAIL')], max_length=50, verbose_name='Type 2FA: TOTP or Email')),
                ('is_enable', models.BooleanField(default=False, verbose_name='Enable 2FA')),
                ('is_priority', models.BooleanField(default=False, verbose_name='Priority 2FA')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth_setting', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User 2FA setting',
                'verbose_name_plural': 'User 2FA setting',
                'unique_together': {('user', 'type')},
            },
        ),
        migrations.DeleteModel(
            name='UserTwoFactorAuthType',
        ),
    ]
