# Generated by Django 5.2.1 on 2025-05-30 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_usertwofactorauthsetting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdeactivatereason',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deactivate_reason', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
