# Generated by Django 5.2.1 on 2025-05-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0017_alter_userdeactivatereason_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdeactivatereason',
            name='reason_type',
            field=models.CharField(choices=[('SPAM', 'Suspicious Spam Activity'), ('ABUSE', 'Violation of Terms of Service'), ('ADMIN', 'Frozen by Administrator'), ('FAILED_LOGIN', 'Too many failed login attempts'), ('INACTIVE', 'User Inactive for too long'), ('OTHER', 'Other')], max_length=50, verbose_name='Reason'),
        ),
    ]
