# Generated by Django 5.2.1 on 2025-05-31 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0018_alter_userdeactivatereason_reason_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdeactivatereason',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Deactivate Reason', 'verbose_name_plural': 'User Deactivate Reason'},
        ),
    ]
