# Generated by Django 5.2.1 on 2025-06-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0019_alter_userdeactivatereason_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertwofactorauthsetting',
            name='type',
            field=models.CharField(choices=[('totp', 'TOTP'), ('email', 'EMAIL OTP')], max_length=50, verbose_name='Type 2FA: TOTP or Email'),
        ),
    ]
