# Generated by Django 5.2.1 on 2025-06-03 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0021_alter_usertwofactorauthsetting_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='language',
        ),
    ]
